### ISSUE TITLE
Curso da Udemy

### ISSUE THREAD

**Issue by zekicarvalho** [DanielNery/most-used-words#1]
Esse é o mesmo leitor de legendas desse [curso](https://www.udemy.com/course/aplicacao-desktop-com-javascript-electron-js-e-vue-js/learn/) ou você fez alguma alteração?

**Comment by DanielNery** [comment]
Olá @zekicarvalho , isso mesmo, o repositório está igual ao do curso, estou trabalhando com colegas da faculdade para implementar a API Speech To Text e outras, da IBM Cloud e do Google Cloud Plataform , para fazer tradução das legendas.

**Comment by zekicarvalho** [comment]
@DanielNery massa, isso mesmo que eu estava procurando. valeu.
